version: "3"

services:
  server:
    image: golang:1.20-alpine 
    container_name: shorturl-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/shorturl  # Mount the current directory
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis  # Service name of the Redis container
      REDIS_PORT: 6379

  redis:
    image: redis:latest  # Official Redis image
    container_name: shorturl-redis
    ports:
      - "6379:6379"
