version: "3"

services:
  server:
    image: ayush5588/shorturl:0.0.4 
    container_name: shorturl-server
    ports:
      - "8080:8080"
    volumes:
      - .:/shorturl  # Mount the current directory
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis  # Service name of the Redis container
      REDIS_PORT: 6379

  redis:
    image: redis:alpine
    container_name: shorturl-redis
    ports:
      - "6379:6379"
